name: CI PIPELINE
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up dotnet v9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet restore MyWebApp.csproj
      - run: dotnet build MyWebApp.csproj --no-restore
      - run: dotnet test tests/MyWebApp.Tests/MyWebApp.Tests.csproj